export const projectsData = [
	{
		id: 1,
		title: "Creative Art Work",
		category: "Branding",
		image: "1.jpg",
		filterValue: "branding",
		toBeRemoved: false,
	},
	{
		id: 2,
		title: "Flowers In Vases",
		category: "Photography",
		image: "2.jpg",
		filterValue: "photography",
		toBeRemoved: false,
	},
	{
		id: 3,
		title: "Art Design",
		category: "UI/UX Design",
		image: "3.jpg",
		filterValue: "ui",
		toBeRemoved: false,
	},
	{
		id: 4,
		title: "Open Books",
		category: "Creative",
		image: "4.jpg",
		filterValue: "creative",
		toBeRemoved: false,
	},
	{
		id: 5,
		title: "Open Books",
		category: "Branding",
		image: "5.jpg",
		filterValue: "branding",
		toBeRemoved: false,
	},
	{
		id: 6,
		title: "Open Books",
		category: "UI/UX Design",
		image: "6.jpg",
		filterValue: "ui",
		toBeRemoved: false,
	},
	{
		id: 7,
		title: "Work Station",
		category: "Photography",
		image: "7.jpg",
		filterValue: "photography",
		toBeRemoved: false,
	},
	{
		id: 8,
		title: "Flowers In Vases",
		category: "Creative",
		image: "8.jpg",
		filterValue: "creative",
		toBeRemoved: false,
	},
	{
		id: 9,
		title: "Creative Art Work",
		category: "Branding",
		image: "9.jpg",
		filterValue: "branding",
		toBeRemoved: false,
	},
];
